defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      type: posts
      path: gigs

    values:
      layout: gig

  -
    scope:
      type: posts
      path: blog

    values:
      layout: blost

permalink: pretty
